### ISSUE TITLE
Possible incompatibility with Mo' Creatures

### ISSUE THREAD

**Issue by Nevvie** [bl4ckscor3/Scarecrows#1]
I was testing the super scary scarecrow. It was fine for, like 10-15 min before it crashed. The crash log:
<details><summary>Expand</summary>
<p>

---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2018-10-13 22:04:24 SGT
Description: Ticking entity

java.util.ConcurrentModificationException
    at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
    at java.util.ArrayList$Itr.next(ArrayList.java:851)
    at net.minecraft.world.World.getEntities(World.java:3035)
    at bl4ckscor3.mod.scarecrows.ai.EntityAIRunAway.shouldExecute(EntityAIRunAway.java:61)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:94)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:885)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2352)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:678)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at drzhark.mocreatures.entity.MoCEntityAnimal.onLivingUpdate(MoCEntityAnimal.java:359)
    at drzhark.mocreatures.entity.MoCEntityTameableAnimal.onLivingUpdate(MoCEntityTameableAnimal.java:425)
    at drzhark.mocreatures.entity.passive.MoCEntityBigCat.onLivingUpdate(MoCEntityBigCat.java:293)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2172)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:377)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zck000(World.java:5117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Thread.java:745)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Entity being ticked --
  Entity Type: mocreatures:leopard (drzhark.mocreatures.entity.passive.MoCEntityLeopard)
  Entity ID: 36988
  Entity Name: Leopard
  Entity's Exact location: -18.50, 119.00, 137.50
  Entity's Block location: World: (-19,119,137), Chunk: (at 13,7,9 in -2,8; contains blocks -32,0,128 to -17,255,143), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Entity's Momentum: 0.00, -0.08, 0.00
  Entity's Passengers: []
  Entity's Vehicle: ~~ERROR~~ NullPointerException: null
  Entity NBT: {HurtByTimestamp:0,Edad:95,ForgeData:{},Sitting:0b,Attributes:[{Base:25.0d,Name:"generic.maxHealth"},{Base:0.0d,Name:"generic.knockbackResistance"},{Base:0.25d,Name:"generic.movementSpeed"},{Base:0.0d,Name:"generic.armor"},{Base:0.0d,Name:"generic.armorToughness"},{Base:1.0d,Name:"forge.swimSpeed"},{Base:6.0d,Modifiers:[{UUIDMost:-8039389606814658617L,UUIDLeast:-8078719917901889912L,Amount:0.025882878243740273d,Operation:1,Name:"Random spawn bonus"}],Name:"generic.followRange"},{Base:5.0d,Name:"generic.attackDamage"}],Invulnerable:0b,FallFlying:0b,ForcedAge:0,PortalCooldown:0,AbsorptionAmount:0.0f,Name:"",Saddle:0b,FallDistance:0.0f,Tamed:0b,InLove:0,DeathTime:0s,ForgeCaps:{"tinkertoolleveling:entityxp":[]},HandDropChances:[0.085f,0.085f],Adult:1b,PersistenceRequired:0b,Age:0,Motion:[0.0d,-0.0784000015258789d,0.0d],Leashed:0b,UUIDLeast:-6008631184495206573L,Health:25.0f,LeftHanded:0b,TypeInt:1,Air:300s,OnGround:1b,Dimension:0,Rotation:[134.20688f,0.0f],UpdateBlocked:0b,HandItems:[{},{}],ArmorDropChances:[0.085f,0.085f,0.085f,0.085f],Amulet:0b,UUIDMost:3008367978974891613L,Pos:[-18.5d,119.0d,137.5d],Ghost:0b,Fire:-1s,ArmorItems:[{},{},{},{}],CanPickUpLoot:0b,HurtTime:0s,Chested:0b}

-- Affected level --
  Level name: New World Test
  All players: 1 total; [EntityPlayerMP['Balistrier'/37187, l='New World Test', x=-20.24, y=76.10, z=-86.99]]
  Chunk stats: ServerChunkCache: 412 Drop: 56
  Level seed: 4802030607147926454
  Level generator: ID 09 - realistic, ver 0. Features enabled: true
  Level generator options: 
  Level spawn location: World: (-97,64,186), Chunk: (at 15,4,10 in -7,11; contains blocks -112,0,176 to -97,255,191), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
  Level time: 136567 game time, 1712 day time
  Level dimension: 0
  Level storage version: 0x04ABD - Anvil
  Level weather: Rain time: 112759 (now: false), thunder time: 111852 (now: false)
  Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: true

-- System Details --
  Minecraft Version: 1.12.2
  Operating System: Mac OS X (x86_64) version 10.13.6
  Java Version: 1.8.0_74, Oracle Corporation
  Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
  Memory: 1125644096 bytes (1073 MB) / 4294967296 bytes (4096 MB) up to 4294967296 bytes (4096 MB)
  JVM Flags: 8 total; -XX:+UseG1GC -Xmx4G -Xms4G -XX:+UnlockExperimentalVMOptions -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
  IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 96
  FML: MCP 9.42 Powered by Forge 14.23.5.2769 Optifine OptiFine_1.12.2_HD_U_E2 122 mods loaded, 122 mods active
       States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
       
       | State         | ID                                | Version                  | Source                                                   | Signature                                |
       |:------------- |:--------------------------------- |:------------------------ |:-------------------------------------------------------- |:---------------------------------------- |
       | UCHIJAAAAAAAA | minecraft                         | 1.12.2                   | minecraft.jar                                            | None                                     |
       | UCHIJAAAAAAAA | mcp                               | 9.42                     | minecraft.jar                                            | None                                     |
       | UCHIJAAAAAAAA | FML                               | 8.0.99.99                | forge-1.12.2-14.23.5.2769.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAAAAAA | forge                             | 14.23.5.2769             | forge-1.12.2-14.23.5.2769.jar                            | e3c3d50c7c986df74c645c0ac54639741c90a557 |
       | UCHIJAAAAAAAA | foamfixcore                       | 7.7.4                    | minecraft.jar                                            | None                                     |
       | UCHIJAAAAAAAA | versionchecker                    | 1.3.0                    | [1.12]+VersionChecker-1.3.0.jar                          | None                                     |
       | UCHIJAAAAAAAA | actuallyadditions                 | 1.12.2-r137              | ActuallyAdditions-1.12.2-r137.jar                        | None                                     |
       | UCHIJAAAAAAAA | baubles                           | 1.5.2                    | Baubles-1.12-1.5.2.jar                                   | None                                     |
       | UCHIJAAAAAAAA | actuallybaubles                   | 1.1                      | ActuallyBaubles-1.12-1.1.jar                             | None                                     |
       | UCHIJAAAAAAAA | buildcraftlib                     | 7.99.18                  | buildcraft-7.99.18.jar                                   | None                                     |
       | UCHIJAAAAAAAA | buildcraftcore                    | 7.99.18                  | buildcraft-7.99.18.jar                                   | None                                     |
       | UCHIJAAAAAAAA | buildcraftfactory                 | 7.99.18                  | buildcraft-7.99.18.jar                                   | None                                     |
       | UCHIJAAAAAAAA | buildcrafttransport               | 7.99.18                  | buildcraft-7.99.18.jar                                   | None                                     |
       | UCHIJAAAAAAAA | buildcraftsilicon                 | 7.99.18                  | buildcraft-7.99.18.jar                                   | None                                     |
       | UCHIJAAAAAAAA | additionalpipes                   | 6.0.0.8                  | additionalpipes-6.0.0.8.jar                              | None                                     |
       | UCHIJAAAAAAAA | advanced-fishing                  | 1.3.1                    | Advanced-Fishing-1.12.2-1.3.1.jar                        | None                                     |
       | UCHIJAAAAAAAA | architecturecraft                 | @VERSION@                | architecturecraft-1.12-3.80.jar                          | None                                     |
       | UCHIJAAAAAAAA | endercore                         | 1.12.2-0.5.41            | EnderCore-1.12.2-0.5.41.jar                              | None                                     |
       | UCHIJAAAAAAAA | jei                               | 4.9.1.168                | jei_1.12.2-4.9.1.168.jar                                 | None                                     |
       | UCHIJAAAAAAAA | enderio                           | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | enderiointegrationtic             | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | ctm                               | MC1.12.2-0.3.2.18        | Chisel_CTM-MC1.12.2-0.3.2.18.jar                         | None                                     |
       | UCHIJAAAAAAAA | chisel                            | MC1.12.2-0.2.0.31        | Chisel-MC1.12.2-0.2.0.31.jar                             | None                                     |
       | UCHIJAAAAAAAA | mantle                            | 1.12-1.3.2.24            | Mantle-1.12-1.3.2.24.jar                                 | None                                     |
       | UCHIJAAAAAAAA | tconstruct                        | 1.12.2-2.10.1.87         | TinkersConstruct-1.12.2-2.10.1.87.jar                    | None                                     |
       | UCHIJAAAAAAAA | extrautils2                       | 1.0                      | extrautils2-1.12-1.9.5.jar                               | None                                     |
       | UCHIJAAAAAAAA | biomesoplenty                     | 7.0.1.2394               | BiomesOPlenty-1.12.2-7.0.1.2394-universal.jar            | None                                     |
       | UCHIJAAAAAAAA | plustic                           | 6.5.2.0                  | plustic-6.5.2.0.jar                                      | None                                     |
       | UCHIJAAAAAAAA | taiga                             | 1.12.2-1.3.3             | taiga-1.12.2-1.3.4.jar                                   | None                                     |
       | UCHIJAAAAAAAA | conarm                            | 1.1.2                    | Tinkers_ConstructArmory-1.12.2-1.1.2.jar                 | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
       | UCHIJAAAAAAAA | armoryexpansion                   | 0.2.0                    | armoryexpansion-0.2.0.jar                                | None                                     |
       | UCHIJAAAAAAAA | aroma1997core                     | 2.0.0.0.b160             | Aroma1997Core-1.12.2-2.0.0.0.b160.jar                    | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAAAAAA | aroma1997sdimension               | 2.0.0.2.b83              | Aroma1997s-Dimensional-World-1.12.2-2.0.0.2.b83.jar      | dfbfe4c473253d8c5652417689848f650b2cbe32 |
       | UCHIJAAAAAAAA | attributefix                      | 1.0.3                    | AttributeFix-1.12.2-1.0.3.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAA | baublelicious                     | 1.4.0-4                  | Baublelicious-1.4.0-4.jar                                | None                                     |
       | UCHIJAAAAAAAA | betterbuilderswands               | 0.11.1                   | BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar          | None                                     |
       | UCHIJAAAAAAAA | bibliocraft                       | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                        | None                                     |
       | UCHIJAAAAAAAA | bookshelf                         | 2.3.559                  | Bookshelf-1.12.2-2.3.559.jar                             | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAA | buildcraftbuilders                | 7.99.18                  | buildcraft-7.99.18.jar                                   | None                                     |
       | UCHIJAAAAAAAA | buildcraftenergy                  | 7.99.18                  | buildcraft-7.99.18.jar                                   | None                                     |
       | UCHIJAAAAAAAA | buildcraftrobotics                | 7.99.18                  | buildcraft-7.99.18.jar                                   | None                                     |
       | UCHIJAAAAAAAA | carryon                           | 1.11                     | CarryOn+MC1.12.2+v1.11.jar                               | None                                     |
       | UCHIJAAAAAAAA | cathedral                         | 1.12.2-1.9.7g            | Cathedral-1.12.2-1.9.7g.jar                              | None                                     |
       | UCHIJAAAAAAAA | cd4017be_lib                      | 6.2.6                    | CD4017BE_lib-1.12.2-6.2.6.jar                            | None                                     |
       | UCHIJAAAAAAAA | chesttransporter                  | 2.8.8                    | ChestTransporter-1.12.2-2.8.8.jar                        | None                                     |
       | UCHIJAAAAAAAA | chickens                          | 6.0.4                    | chickens-6.0.4.jar                                       | None                                     |
       | UCHIJAAAAAAAA | chameleon                         | 1.12-4.1.3               | Garden-Chameleon-Library-1.12.jar                        | None                                     |
       | UCHIJAAAAAAAA | storagedrawers                    | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.7.jar                          | None                                     |
       | UCHIJAAAAAAAA | compactdrawers                    | 1.12.2-1.0.3.86          | CompactDrawers-1.12.2-1.0.3.86.jar                       | None                                     |
       | UCHIJAAAAAAAA | corail_pillar_extension_chisel    | 4.0.0                    | corail_pillar_extension_chisel-4.0.0-1.12.jar            | None                                     |
       | UCHIJAAAAAAAA | torohealthmod                     | 1.12.2-11                | Damage-Indicators-1.12.2.jar                             | None                                     |
       | UCHIJAAAAAAAA | ptrmodellib                       | 1.0.3                    | Decocraft2_PTRLib-1.0.3.jar                              | None                                     |
       | UCHIJAAAAAAAA | props                             | 2.6.2                    | Decocraft2_2.6.2_1.12.2.jar                              | None                                     |
       | UCHIJAAAAAAAA | dungeondq                         | 10.00                    | DungeonDQ_Ver10.00_[MC1.12](forge-1.12-14.21.1.2387).jar | None                                     |
       | UCHIJAAAAAAAA | gottschcore                       | 1.5.0                    | Dungeons2_GottschCore-mc1.12.2-f14.23.4.2705-v1.5.0.jar  | None                                     |
       | UCHIJAAAAAAAA | dungeons2                         | 1.3.3                    | Dungeons2-mc1.12-f14.21.1.2387-v1.3.3.jar                | None                                     |
       | UCHIJAAAAAAAA | easyretrogen                      | 5.0.1                    | EasyRetrogen-1.12.2-5.0.1-universal.jar                  | None                                     |
       | UCHIJAAAAAAAA | eplus                             | 5.0.164                  | EnchantingPlus-1.12.2-5.0.164.jar                        | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAA | enderiobase                       | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | enderioconduits                   | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | enderioconduitsappliedenergistics | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | enderioconduitsopencomputers      | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | enderioconduitsrefinedstorage     | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | forestry                          | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                            | None                                     |
       | UCHIJAAAAAAAA | enderiointegrationforestry        | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | enderiointegrationticlate         | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | enderiomachines                   | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | enderiopowertools                 | 5.0.36                   | EnderIO-1.12.2-5.0.36.jar                                | None                                     |
       | UCHIJAAAAAAAA | expandedplates                    | 1.12.2-0.3               | expandedplates-1.12.2-0.3.jar                            | None                                     |
       | UCHIJAAAAAAAA | foamfix                           | 0.10.2-1.12.2            | foamfix-0.10.2-1.12.2.jar                                | None                                     |
       | UCHIJAAAAAAAA | cfm                               | 5.13.0                   | furniture-5.13.0-1.12.2.jar                              | None                                     |
       | UCHIJAAAAAAAA | gravestone                        | 1.1.0                    | GraveStone-1.12.2-Graves-1.1.0.jar                       | None                                     |
       | UCHIJAAAAAAAA | hatchery                          | 2.1.3                    | hatchery-1.12.2-2.1.3.jar                                | None                                     |
       | UCHIJAAAAAAAA | waila                             | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                              | None                                     |
       | UCHIJAAAAAAAA | igwmod                            | 1.4.4-15                 | IGW-Mod-1.12.2-1.4.4-15-universal.jar                    | None                                     |
       | UCHIJAAAAAAAA | indlog                            | 1.3.1                    | InductiveLogistics-1.12.2-1.3.1.jar                      | None                                     |
       | UCHIJAAAAAAAA | industrialrenewal                 | 0.6.0                    | IndustrialRenewal_1.12.2-0.6.0.jar                       | None                                     |
       | UCHIJAAAAAAAA | inventorytweaks                   | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                                 | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
       | UCHIJAAAAAAAA | journeymap                        | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                              | None                                     |
       | UCHIJAAAAAAAA | justenoughbuttons                 | 1.12-1.2.1               | Just-Enough-Buttons-Mod-1.12.1.jar                       | None                                     |
       | UCHIJAAAAAAAA | jeid                              | 1.0.2-25                 | JustEnoughIDs-1.0.2-25.jar                               | None                                     |
       | UCHIJAAAAAAAA | fluidtank                         | 3.3                      | LargeFluidTank-3.3.jar                                   | 617a4e95f0af9de5402bb9883abe0f53a6bfa230 |
       | UCHIJAAAAAAAA | linear                            | 1.2.1                    | Linear+MC1.12.2+v1.2.1.jar                               | None                                     |
       | UCHIJAAAAAAAA | makezoomzoom                      | 0.0.2                    | MakeZoomZoom-0.0.2.jar                                   | None                                     |
       | UCHIJAAAAAAAA | malisiscore                       | 1.12.2-6.4.0             | malisiscore-1.12.2-6.4.0.jar                             | None                                     |
       | UCHIJAAAAAAAA | malisisblocks                     | 1.12.2-6.1.0             | malisisblocks-1.12.2-6.1.0.jar                           | None                                     |
       | UCHIJAAAAAAAA | malisisdoors                      | 1.12.2-7.3.0             | malisisdoors-1.12.2-7.3.0.jar                            | None                                     |
       | UCHIJAAAAAAAA | malisisswitches                   | 1.12.2-5.1.0             | malisisswitches-1.12.2-5.1.0.jar                         | None                                     |
       | UCHIJAAAAAAAA | millenaire                        | Millénaire 6.2.10        | millenaire-1.12.2-6.2.10.jar                             | None                                     |
       | UCHIJAAAAAAAA | customspawner                     | 3.11.3                   | Mo-Creatures-Custom-Mob-Spawner-Mod-1.12.2.jar           | None                                     |
       | UCHIJAAAAAAAA | mocreatures                       | 12.0.3                   | Mo-Creatures-Mod-1.12.2.jar                              | None                                     |
       | UCHIJAAAAAAAA | mob_grinding_utils                | 0.3.7                    | MobGrindingUtils-0.3.7.jar                               | None                                     |
       | UCHIJAAAAAAAA | modernlamps                       | 1.0.3                    | Modern-Lights-Mod-1.12.jar                               | None                                     |
       | UCHIJAAAAAAAA | modularrouters                    | 1.12.2-3.2.1             | modular-routers-1.12.2-3.2.1.jar                         | None                                     |
       | UCHIJAAAAAAAA | multiplelights                    | 1.0                      | Multiple-Lights-Mod-1.12.2.jar                           | None                                     |
       | UCHIJAAAAAAAA | recipehandler                     | 0.11                     | NoMoreRecipeConflict-0.11(1.12.2).jar                    | None                                     |
       | UCHIJAAAAAAAA | nt                                | 1.0                      | Novam+Terram+1.12.2+-+5.0.jar                            | None                                     |
       | UCHIJAAAAAAAA | oresalleasy                       | 0.1.0.22                 | OresAllEasy-1.12.2-0.1.0.22.jar                          | None                                     |
       | UCHIJAAAAAAAA | persistentbits                    | 1.0.6a                   | PersistentBits-1.12-1.0.6a.jar                           | None                                     |
       | UCHIJAAAAAAAA | quickleafdecay                    | 1.2.4                    | QuickLeafDecay-MC1.12.1-1.2.4.jar                        | None                                     |
       | UCHIJAAAAAAAA | randomtweaks                      | 1.12.2-2.1.7.1           | randomtweaks-1.12.2-2.1.7.1.jar                          | None                                     |
       | UCHIJAAAAAAAA | rationcraft                       | 1.0                      | Rationcraft_B1.0.1_1.12.2.jar                            | None                                     |
       | UCHIJAAAAAAAA | recycler                          | 3.2.2                    | recycler-3.2.2-1.12.jar                                  | None                                     |
       | UCHIJAAAAAAAA | scarecrows                        | v1.0                     | scarecrows-1.12.x-v1.0.jar                               | None                                     |
       | UCHIJAAAAAAAA | simplyloaders                     | 1.0.0                    | Simplyloaders-2.0.jar                                    | None                                     |
       | UCHIJAAAAAAAA | surge                             | 2.0.72                   | Surge-1.12.2-2.0.72.jar                                  | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAA | telex                             | 1.0.2                    | Telex-1.0.2-mc1.12.1to1.12.2-forge.jar                   | None                                     |
       | UCHIJAAAAAAAA | texfix                            | 4.0                      | TexFix-Mod-1.12.2.jar                                    | None                                     |
       | UCHIJAAAAAAAA | thutcore                          | 5.16.3                   | thutcore-1.12.2-5.16.3.jar                               | None                                     |
       | UCHIJAAAAAAAA | thutcore_compat                   | 1.0                      | thutcore-1.12.2-5.16.3.jar                               | None                                     |
       | UCHIJAAAAAAAA | thuttech                          | 6.0.16                   | thuttech-1.12.2-6.0.16.jar                               | None                                     |
       | UCHIJAAAAAAAA | tinkersarsenal                    | 0.5                      | tinkersarsenal-0.5.jar                                   | None                                     |
       | UCHIJAAAAAAAA | tinkersjei                        | 1.0                      | tinkersjei-1.0.jar                                       | None                                     |
       | UCHIJAAAAAAAA | tinkertoolleveling                | 1.12.2-1.0.5.DEV.30c7957 | TinkerToolLeveling-1.12.2-1.0.5.jar                      | None                                     |
       | UCHIJAAAAAAAA | buildhelper                       | 1.0.2                    | torojimaBuildHelper-1.0.2.jar                            | None                                     |
       | UCHIJAAAAAAAA | v0idssmartbackpacks               | 1.0.6                    | V0id's+Smart+Backpacks-1.0.6.jar                         | None                                     |
       | UCHIJAAAAAAAA | vanillafix                        | 1.0.9-97                 | VanillaFix-1.0.9-97.jar                                  | None                                     |
       | UCHIJAAAAAAAA | wawla                             | 2.5.261                  | Wawla-1.12.2-2.5.261.jar                                 | d476d1b22b218a10d845928d1665d45fce301b27 |
       | UCHIJAAAAAAAA | xlfoodmod                         | 1.12.2-1.7.1             | XL-Food-Mod-1.12.2-1.7.1.jar                             | None                                     |
       | UCHIJAAAAAAAA | btdc                              | 1.2                      | btdc-1.2.jar                                             | None                                     |
       | UCHIJAAAAAAAA | shetiphiancore                    | 3.5.7                    | platforms_shetiphiancore-1.12.0-3.5.7.jar                | None                                     |
       | UCHIJAAAAAAAA | corail_pillar                     | 4.1.0                    | corail_pillar-4.1.0-1.12.jar                             | None                                     |
  Loaded coremods (and transformers): MalisisSwitchesPlugin (malisisswitches-1.12.2-5.1.0.jar)
                                        
                                      EnderCorePlugin (EnderCore-1.12.2-0.5.41.jar)
                                        com.enderio.core.common.transform.EnderCoreTransformer
                                        com.enderio.core.common.transform.SimpleMixinPatcher
                                      VanillaFixLoadingPlugin (VanillaFix-1.0.9-97.jar)
                                        
                                      CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b160.jar)
                                        
                                      CTMCorePlugin (Chisel_CTM-MC1.12.2-0.3.2.18.jar)
                                        team.chisel.ctm.client.asm.CTMTransformer
                                      MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
                                        
                                      Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
                                        invtweaks.forge.asm.ContainerTransformer
                                      JEIDLoadingPlugin (JustEnoughIDs-1.0.2-25.jar)
                                        org.dimdev.jeid.JEIDTransformer
                                      SurgeLoadingPlugin (Surge-1.12.2-2.0.72.jar)
                                        
                                      Do not report to Forge! (If you haven't disabled the FoamFix coremod, try disabling it in the config! Note that this bit of text will still appear.) (foamfix-0.10.2-1.12.2.jar)
                                        pl.asie.foamfix.coremod.FoamFixTransformer
                                      ShetiPhian-ASM (shetiphian-asm.jar)
                                        shetiphian.asm.ClassTransformer
                                      MZZLoadingPlugin (MakeZoomZoom-0.0.2.jar)
                                        xyz.ajp.makezoomzoom.asm.MZZClassTransformer
                                      LoadingPlugin ([1.12]+VersionChecker-1.3.0.jar)
  Pulsar/tconstruct loaded Pulses: - TinkerCommons (Enabled/Forced)
                                   - TinkerWorld (Enabled/Not Forced)
                                   - TinkerTools (Enabled/Not Forced)
                                   - TinkerHarvestTools (Enabled/Forced)
                                   - TinkerMeleeWeapons (Enabled/Forced)
                                   - TinkerRangedWeapons (Enabled/Forced)
                                   - TinkerModifiers (Enabled/Forced)
                                   - TinkerSmeltery (Enabled/Not Forced)
                                   - TinkerGadgets (Enabled/Not Forced)
                                   - TinkerOredict (Enabled/Forced)
                                   - TinkerIntegration (Enabled/Forced)
                                   - TinkerFluids (Enabled/Forced)
                                   - TinkerMaterials (Enabled/Forced)
                                   - TinkerModelRegister (Enabled/Forced)
                                   - chiselIntegration (Enabled/Not Forced)
                                   - wailaIntegration (Enabled/Not Forced)
  Ender IO: Found the following problem(s) with your installation (That does NOT mean that Ender IO caused the crash or was involved in it in any way. We add this information to help finding common problems, not as an invitation to post any crash you encounter to Ender IO's issue tracker. Always check the stack trace above to see which mod is most likely failing.):
                              * Optifine is installed. This is NOT supported.
                             This may (look up the meaning of 'may' in the dictionary if you're not sure what it means) have caused the error. Try reproducing the crash WITHOUT this/these mod(s) before reporting it.
            
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
            !!!You are looking at the diagnostics information, not at the crash.       !!!
            !!!Scroll up until you see the line with '---- Minecraft Crash Report ----'!!!
            !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  Suspected Mods: Scarecrows (scarecrows), DrZhark's Mo'Creatures Mod (mocreatures)
  Profiler Position: N/A (disabled)
  Player Count: 1 / 8; [EntityPlayerMP['Balistrier'/37187, l='New World Test', x=-20.24, y=76.10, z=-86.99]]
  Type: Integrated Server (map_client.txt)
  Is Modded: Definitely; Client brand changed to 'fml,forge'

</p>
</details>

**Comment by bl4ckscor3** [comment]
Does this happen more often, or is this a one time thing?

To explain the crash:
A ConcurrentModificationException happens when a list is getting modified while also being accessed at the same time. The line of code in my mod that is referenced by the crashlog only retrieves said list, and does not modify it, hence the cause of this crash isn't there. I would assume that either a different mod, or vanilla Minecraft itself is modifying the list while my mod tries to access it. I honestly don't know what I can do about this as, like I mentioned, I'm just retrieving a list without modifying it.

I will leave this open for now, should someone else have any input for this, but I doubt that I can resolve it.

**Comment by Nevvie** [comment]
I'm not sure, I might have to test some more. After it crashed, I opened the world again without changing anything, and it crashed immediately. I removed the scarecrow mod and my world can be played again. 
I'm gonna try putting the mod in again and testing in a new world without mo' creatures when I'm free.

**Comment by bl4ckscor3** [comment]
Please try out the newest beta build on CurseForge and report back whether you run into the issue.

**Comment by bl4ckscor3** [comment]
By some testing on the MMD server, it looks like this is fixed by 6824a44387b985f7fd4a37710fc5a126722b74d9 in v1.0.3.
