### ISSUE TITLE
Ticking entity?

### ISSUE THREAD

**Issue by tinklesdawn** [bl4ckscor3/Scarecrows#11]
Some random crashes happen more and more often. Last time they happened 3 times in 10 min. There are series of the same crash reports, the only difference in the entity ticking.
[crash-2022-07-20_16.38.21-server.txt](https://github.com/bl4ckscor3/Scarecrows/files/9148699/crash-2022-07-20_16.38.21-server.txt)

**Comment by bl4ckscor3** [comment]
Please try out this version and report back whether it works for you. https://www.curseforge.com/minecraft/mc-mods/scarecrows/files/3886116 (As of writing, it may not be available, pending approval by CurseForge)

**Comment by tinklesdawn** [comment]
Everything works fine! 4 hours and zero crashes. Thank you!
