### ISSUE TITLE
Crash scarecrow:arm it is not allowed

### ISSUE THREAD

**Issue by jbjmed** [bl4ckscor3/Scarecrows#3]
Getting the following when client crashes. 

java.lang.IllegalArgumentException: Cannot set property PropertyDirection{name=facing, clazz=class net.minecraft.util.EnumFacing, values=[north, south, west, east]} to up on block scarecrows:arm, it is not an allowed value

Full log 
[crash-2018-10-23_20.28.05-client.txt](https://github.com/bl4ckscor3/Scarecrows/files/2508658/crash-2018-10-23_20.28.05-client.txt)

**Comment by bl4ckscor3** [comment]
Already fixed by 0308c4f6ff7f2535aea5782643e6ce145a1564ae and 8f38b6b834fefbdb2296d7a8b3bd54829acefcfc in  v1.0.3.
