### ISSUE TITLE
Client crash 1.14.2

### ISSUE THREAD

**Issue by ProsperCraft** [bl4ckscor3/Scarecrows#5]
Adding this to my Forge 1.14.2 version 32 causes a crash on load.

https://gist.github.com/ProsperCraft/c1a11b489b7e93c8b85be3ea8b17ad2f

removing it stops the crash, putting it back causes it again.

**Comment by bl4ckscor3** [comment]
I cannot reproduce the crash with Scarecrows v1.0.6 and Forge 26.0.32. Are you using any other mods perhaps?

**Comment by ProsperCraft** [comment]
Well, you are correct, I just tested with a clean install on a different computer, I will narrow down which mod it is conflicting with and let you know.

**Comment by ProsperCraft** [comment]
I don't know if it was the update to forge or what, but it is no longer crashing and I have 33 mods installed now.
