### ISSUE TITLE
Zombies with Zombie Awareness

### ISSUE THREAD

**Issue by Jack-Chronicle** [bl4ckscor3/Scarecrows#6]
Zombie Awareness overrides the zombies from running away, once they start tracking a player they seem to ignore the scarecrows entirely, even when right next to the Scary Scarecrow and Super variant, they just group up and attack the player.
Possibly bug, or could just need to add compatibility between them? Figured i'd bring it up

**Comment by bl4ckscor3** [comment]
Can't seem to reproduce. When I lure a zombie into the range of a scarecrow, he'll run away, then try to attack me again once he is outside the range of the scarecrow. Could you please give me some steps so I can reproduce the issue?
