### ISSUE TITLE
Performance issue - bl4ckscor3.mod.scarecrows.ai.EntityAIRunAway.shouldExecute()11.98%12500ms

### ISSUE THREAD

**Issue by ProsperCraft** [bl4ckscor3/Scarecrows#8]
https://gyazo.com/e7a361291b7948bd2fdfd14fd50883f5

Nobody on the server has intentionally made a scarecrow, but the server is struggling and a warmroast is showing the mobs are all trying to see if they need to flee from scarecrows.

Removing the mod from the pack.

**Comment by bl4ckscor3** [comment]
I implemented some changes to counteract this. I'll test them later with LagGoggles and WarmRoast.

**Comment by bl4ckscor3** [comment]
From my testing everything looks fine. It would be awesome if you could report back whether v1.0.8 works for you. https://www.curseforge.com/minecraft/mc-mods/scarecrows/files/2735430

**Comment by bl4ckscor3** [comment]
Assuming everything is fine.
